### ISSUE TITLE
Automatiske tester for generering av tekststrenger

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/service-stem#2]
For eksempel:

```yml
test:
  - input: "<m:math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><m:mfenced open="(" close=")"><m:mrow><m:mi>x</m:mi><m:mo>+</m:mo><m:mi>y</m:mi></m:mrow></m:mfenced><m:mo>&#8290;</m:mo><m:mfenced open="(" close=")"><m:mrow><m:mi>x</m:mi><m:mo>+</m:mo><m:mi>y</m:mi></m:mrow></m:mfenced></m:math>"
  - expect: "formula left parenthesis x plus y right parenthesis times left parenthesis x plus y right parenthesis formula end"
```

Gjerne med ASCIIMath som `input` sånn at det er enklere å lese for et menneske.

For å lage masse tester kan vi f.eks. finne en formelsamling, eller andre sett med formler.
